### ISSUE TITLE
点数マイナス時の追加が出来ない問題

### ISSUE THREAD

**Issue by KRei0** [ltoppyl/mahjong-score-manage#62]
## 🐛 概要

点数がマイナスの時、記録できない問題が発生
点数がプラスの時は実行できているため、プラス、マイナスボタンに問題があるのでは?

## 📸 スクリーンショット
![image](https://user-images.githubusercontent.com/117695498/234001039-1d27d702-3ae6-46ce-a050-9a9466d64f76.png)

## 👀 再現手順

1. 点数入力画面に数値を入力
2. マイナスボタンをクリックし、文字を赤色にする
3. 追加ボタンを押すと、追加できない

## 🎨 期待する挙動

点数がプラスの時と同様に記録ができるようにする

## 📦️ 環境

- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge

## ✅ タスク

- [ ] 点数の保存ができる
- [ ] 動作確認ができる

**Comment by ltoppyl** [comment]
スコアを入力する前に、マイナスボタンを押した場合に失敗していることを確認した
